---
title: "Curriculum Vitae"
format:
  pdf:
    pdf-engine: xelatex
    fontsize: 12pt
    mainfont: "Times New Roman"
    geometry:
      - top=3cm
      - bottom=2cm
      - left=3cm
      - right=2cm
---

```{r}
#| include: false

# Configurações globais dos blocos de código
knitr::opts_chunk$set(
  echo = TRUE,
  fig.crop = FALSE  # DESATIVA o pdfcrop para evitar o erro fatal do MiKTeX
)

# Ativa o modo detalhado para identificar outros problemas de compilação
options(tinytex.verbose = TRUE)

# Garante a codificação correta dos caracteres em português
Sys.setlocale("LC_CTYPE", "pt_BR.UTF-8")
```


## Dados Pessoais

**Nome:** Valdenise Noberto dos Santos
**Nacionalidade:** Brasileira
**Estado Civil:** Solteira
**Sexo:** Feminino
**Data de Nascimento:** 09/03/1992
**Idade:** 34 anos
**Endereço:** Rua Sizenando Paulino da Paixão, 354, Centro, Pedra Lavrada/PB
**Celular:** (83) 98184-1349
**WhatsApp:** (83) 98184-1349
**Lattes:** [http://cnpq.br](https://lattes.cnpq.br/0640290162907725)
**LinkedIn:** [https://www.linkedin.com/in/valdenise-noberto-santos-876803298/](https://www.linkedin.com/in/valdenise-noberto-santos-876803298/)
**E-mail:** valdenisenoberto2018@gmail.com

## Formação Acadêmica

* **Graduação em Licenciatura em Matemática (Licenciatura Plena)**
  * Instituição: Universidade Federal de Campina Grande (UFCG)
  * Cidade: Cuité - PB
  * Conclusão: Dezembro de 2015

* **Graduação em Estatística (Bacharelado)**
  * Instituição: Universidade Estadual da Paraíba (UEPB)
  * Cidade: Campina Grande – PB
  * Situação: Em andamento

* **Pós-Graduação: Especialização em Ensino de Matemática para o Ensino Médio**
  * Instituição: Instituto Federal de Educação, Ciências e Tecnologia do Rio Grande do Norte (IFRN)
  * Cidade: Natal – RN
  * Situação: Em andamento

## Experiência Profissional

* **Escola Municipal de Ensino Fundamental Ana Maria Gomes**
  * Cidade: Nova Picuí - Paraíba
  * Cargo: Professora
  * Período: 09/04/2019 a 26/12/2019
  * Funções: Ensino de Matemática no Ensino Fundamental (7° e 8° ano)

* **Escola Municipal de Ensino Fundamental Maria Elenita de Vasconcelos Carvalho**
  * Cidade: Pedra Lavrada - Paraíba
  * Cargo: Professora
  * Período: Anos Letivos de 2016 e 2017
  * Funções: Ensino de Matemática no Ensino Fundamental (6° a 9° ano) e EJA; Monitora Voluntária do Projeto Mais Educação

## Qualificação e Atividades Complementares

* **Voluntária em Projeto de Extensão - Circo da Ciência**
  * Título: Circo da Ciência – Experimentação para Contextualização
  * Instituição: Universidade Federal de Campina Grande (UFCG)
  * Carga horária: 192 horas | Ano: 2013
  * Descrição: Espaço itinerante com apresentações de experimentos de Química, Física, Biologia e Matemática nas escolas.

* **Voluntária em Projeto de Extensão - Pré-Vestibular**
  * Título: Curso Pré-Vestibular Solidário
  * Instituição: Universidade Federal de Campina Grande (UFCG)
  * Carga horária: 120 hours | Ano: 2013
  * Descrição: Professora da disciplina de Matemática.
